name: Ubuntu GPU

on: [push, pull_request]

jobs:
  gpu:
    runs-on: [self-hosted, Linux, X64]
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: |
        python -m pip install ".[dev]" --upgrade
    - name: wandb login
      run: |
        wandb login e2366d661b89f2bee877c40bee15502d67b7abef
    - name: Test with pytest
      # ignore test/throughput which only profiles the code
      run: |
        pytest test --ignore-glob='*profile.py' --cov=tianshou --cov-report=xml --durations=0 -v --color=yes
