name: PEP8, Types and Docs Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous run
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install dependencies
      run: |
        python -m pip install ".[dev]" --upgrade
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Code formatter
      run: |
        yapf -r -d .
        isort --check .
    - name: Type check
      run: |
        mypy
    - name: Documentation test
      run: |
        make check-docstyle
        make spelling
