python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave1" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave1" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave1" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave1" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave1" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave1" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave1" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave1" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave1" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave1" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave1" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave1" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave1" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave1" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave1" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 1 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave1" &


python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave2" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave2" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave2" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave2" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave2" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave2" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave2" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave2" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave2" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave2" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave2" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave2" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave2" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave2" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave2" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 2 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave2" &



python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave3" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave3" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave3" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave3" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave3" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave3" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave3" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave3" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave3" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave3" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave3" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave3" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave3" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave3" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave3" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 3 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave3" &


python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 0   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave4" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 1   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave4" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 2   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave4" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 3   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave4" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave4" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave4" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave4" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave4" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave4" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave4" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave4" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave4" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave4" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave4" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave4" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 4 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave4" &

python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 0   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave5" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 1   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave5" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 2   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave5" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 3   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave5" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 0   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave5" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 1   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave5" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 2   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave5" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 3   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave5" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave5" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave5" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave5" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave5" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave5" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave5" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave5" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 5 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave5" &


python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 0   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave6" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 1   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave6" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 2   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave6" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 3   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave6" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave6" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave6" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave6" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave6" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave6" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 6   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave6" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 5   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave6" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 4   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave6" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave6" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave6" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave6" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 6 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave6" &



python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave7" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave7" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave7" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave7" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave7" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave7" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave7" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave7" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave7" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave7" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave7" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave7" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave7" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave7" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave7" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 7 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave7" &


python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave8" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave8" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave8" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave8" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave8" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave8" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave8" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave8" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave8" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave8" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave8" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave8" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave8" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave8" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave8" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 8 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave8" &


python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave9" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave9" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave9" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave9" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave9" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave9" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave9" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave9" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave9" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave9" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave9" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave9" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave9" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave9" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave9" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 9 --leave_threshold 0 --which_tracker avg  --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave9" &


python run_Policy_SQN.py  --env KuaiEnv-v0   --seed 0 --cuda 4   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave10" &
python run_Policy_CRR.py  --env KuaiEnv-v0   --seed 0 --cuda 5   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave10" &
python run_Policy_CQL.py  --env KuaiEnv-v0   --seed 0 --cuda 6   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave10" &
python run_Policy_BCQ.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave10" &
python run_Policy_IPS.py  --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "DeepFM-IPS"  --message "IPS-leave10" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MBPO-leave10" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 0    --window_size 3 --read_message "pointneg"    --message "MOPO-leave10" &
python run_Policy_Main.py --env KuaiEnv-v0   --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.05 --lambda_entropy 5    --window_size 3 --read_message "pointneg"    --message "DORL-leave10" &
python run_Policy_SQN.py  --env KuaiRand-v0  --seed 0 --cuda 3   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "SQN-leave10" &
python run_Policy_CRR.py  --env KuaiRand-v0  --seed 0 --cuda 2   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --window_size 3 --read_message "pointneg"  											   --message "CRR-leave10" &
python run_Policy_CQL.py  --env KuaiRand-v0  --seed 0 --cuda 1   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --num-quantiles 20 --min-q-weight 10 --window_size 3 --read_message "pointneg"            --message "CQL-leave10" &
python run_Policy_BCQ.py  --env KuaiRand-v0  --seed 0 --cuda 0   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --unlikely-action-threshold 0.6 --window_size 3 --read_message "pointneg"                 --message "BCQ-leave10" &
python run_Policy_IPS.py  --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "DeepFM-IPS" --message "IPS-leave10" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0    --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MBPO-leave10" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0     --window_size 3 --read_message "pointneg"   --message "MOPO-leave10" &
python run_Policy_Main.py --env KuaiRand-v0  --seed 0 --cuda 7   --num_leave_compute 10 --leave_threshold 0 --which_tracker avg --reward_handle "cat" --lambda_variance 0.01 --lambda_entropy 0.05  --window_size 3 --read_message "pointneg"   --message "DORL-leave10" &


python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 0 --epoch 3 --num_leave_compute 1  --leave_threshold 0 --loss "pointneg" --message "UCB-leave1" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 1 --epoch 3 --num_leave_compute 2  --leave_threshold 0 --loss "pointneg" --message "UCB-leave2" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 2 --epoch 3 --num_leave_compute 3  --leave_threshold 0 --loss "pointneg" --message "UCB-leave3" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 3 --epoch 3 --num_leave_compute 4  --leave_threshold 0 --loss "pointneg" --message "UCB-leave4" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 4 --epoch 3 --num_leave_compute 5  --leave_threshold 0 --loss "pointneg" --message "UCB-leave5" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 5 --epoch 3 --num_leave_compute 6  --leave_threshold 0 --loss "pointneg" --message "UCB-leave6" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 6 --epoch 3 --num_leave_compute 7  --leave_threshold 0 --loss "pointneg" --message "UCB-leave7" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 7 --epoch 3 --num_leave_compute 8  --leave_threshold 0 --loss "pointneg" --message "UCB-leave8" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 0 --epoch 3 --num_leave_compute 9  --leave_threshold 0 --loss "pointneg" --message "UCB-leave9" &
python run_linUCB.py         --env KuaiRand-v0  --seed 0 --cuda 1 --epoch 3 --num_leave_compute 10 --leave_threshold 0 --loss "pointneg" --message "UCB-leave10" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 2 --epoch 3 --num_leave_compute 1  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave1" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 3 --epoch 3 --num_leave_compute 2  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave2" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 7 --epoch 3 --num_leave_compute 3  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave3" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 6 --epoch 3 --num_leave_compute 4  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave4" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 5 --epoch 3 --num_leave_compute 5  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave5" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 4 --epoch 3 --num_leave_compute 6  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave6" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 3 --epoch 3 --num_leave_compute 7  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave7" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 2 --epoch 3 --num_leave_compute 8  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave8" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 1 --epoch 3 --num_leave_compute 9  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave9" &
python run_epsilongreedy.py  --env KuaiRand-v0  --seed 0 --cuda 0 --epoch 3 --num_leave_compute 10 --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave10" &



python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 0 --epoch 3 --num_leave_compute 1  --leave_threshold 0 --loss "pointneg" --message "UCB-leave1" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 1 --epoch 3 --num_leave_compute 2  --leave_threshold 0 --loss "pointneg" --message "UCB-leave2" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 2 --epoch 3 --num_leave_compute 3  --leave_threshold 0 --loss "pointneg" --message "UCB-leave3" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 3 --epoch 3 --num_leave_compute 4  --leave_threshold 0 --loss "pointneg" --message "UCB-leave4" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 4 --epoch 3 --num_leave_compute 5  --leave_threshold 0 --loss "pointneg" --message "UCB-leave5" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 5 --epoch 3 --num_leave_compute 6  --leave_threshold 0 --loss "pointneg" --message "UCB-leave6" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 6 --epoch 3 --num_leave_compute 7  --leave_threshold 0 --loss "pointneg" --message "UCB-leave7" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 7 --epoch 3 --num_leave_compute 8  --leave_threshold 0 --loss "pointneg" --message "UCB-leave8" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 4 --epoch 3 --num_leave_compute 9  --leave_threshold 0 --loss "pointneg" --message "UCB-leave9" &
python run_linUCB.py         --env KuaiEnv-v0  --seed 0 --cuda 5 --epoch 3 --num_leave_compute 10 --leave_threshold 0 --loss "pointneg" --message "UCB-leave10" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 6 --epoch 3 --num_leave_compute 1  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave1" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 7 --epoch 3 --num_leave_compute 2  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave2" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 7 --epoch 3 --num_leave_compute 3  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave3" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 6 --epoch 3 --num_leave_compute 4  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave4" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 5 --epoch 3 --num_leave_compute 5  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave5" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 4 --epoch 3 --num_leave_compute 6  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave6" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 3 --epoch 3 --num_leave_compute 7  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave7" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 2 --epoch 3 --num_leave_compute 8  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave8" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 1 --epoch 3 --num_leave_compute 9  --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave9" &
python run_epsilongreedy.py  --env KuaiEnv-v0  --seed 0 --cuda 0 --epoch 3 --num_leave_compute 10 --leave_threshold 0 --loss "pointneg" --message "epsilon-greedy-leave10" &